### ISSUE TITLE
App incompatible?

### ISSUE THREAD

**Issue by michalsukupcak** [umanx/DashNotifier#1]
Hi there. Can I just ask why does the app (on Play Store) claim to be incompatible with Galaxy S III International (gt-i9300) running Cyanogenmod 10.2 (Android 4.3)?

It works perfectly ok using the apk from XDA forum.

**Comment by umanx** [comment]
Hi. I run this on CM 10.2 on Galaxy S II International myself. I have no idea why you see it as incompatible. There are no device or region restrictions set on Play Store either.

**Comment by michalsukupcak** [comment]
I waited for day and tried again and suddenly Play Store lets me install app like it should. Sorry for the false alarm. :)
